
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef 发发发_H
#define 发发发_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 发发发_valueRangeTest (UNS8 typeValue, void * value);
const CONSTSTORE indextable * 发发发_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data 发发发_Data;
extern UNS8 _111ds;		/* Mapped at index 0x2000, subindex 0x00*/

#endif // 发发发_H
